### PR TITLE
build: properly check for the staging directory presence

### PR DESCRIPTION
**Pull request by philn**
Fixes regression introduced in 6ec913df3d1f487927f644f01dcce040737ff553

### CODE REVIEW

**Comment by lokesku** [comment]
Sravan > PLease review this change.

**Comment by ssravan** [comment]
This syntax looks good to me.

**Comment by lokesku** [comment]
I guess this change is not needed. I am closing the pull request. We need to define the MACROS in our environment for this to build.

**Comment by philn** [comment]
hum really? Did I miss something?

**Comment by lokesku** [comment]
Sorry.. wrong pull request.

**Pull request closed without merging**
